### ISSUE TITLE
A4.1 - Añadir GET para las búsquedas en DataSvc

### ISSUE THREAD

**Issue by carlosatyca** [Stacking-Up/data-service#10]
Añadir el parámetro "search" en la query del endpoint GET de espacios en Data Service. La idea es que al buscar una ciudad, por ejemplo "Sevilla", se ejecuta la llamada a /api/v1/spaces?search="Sevilla" que busca la palabra "Sevilla" en el título, descripción y localización del espacio.

**Comment by alesancor1** [comment]
Funcionalidad impletada. Ver #28
