### ISSUE TITLE
A7.1 – PUT / POST / DELETE en el dataService

### ISSUE THREAD

**Issue by tomgalbar** [Stacking-Up/data-service#19]
Añadir los endpoints:
- [x] POST /api/v1/spaces (requiere JWT)
- [x] PUT /api/v1/spaces/{spaceId} (requiere JWT)
- [x] DELETE /api/v1/spaces/{spaceId} (requiere JWT)

**Comment by alesancor1** [comment]
Funcionalidad implementada correctamente. Ver #27
