### ISSUE TITLE
RA1.3 - Refactorizar backend

### ISSUE THREAD

**Issue by tomgalbar** [Stacking-Up/data-service#39]
## Detalles
Se deberá mejorar el código en general, cumplimentando la lista de subtareas que se detalla a continuación:

## Subtareas
- [x] Función de cálculo de precios (movida desde frontend)
- Tener en cuenta tipo de alquiler/es, metros alquilados (si es compartido)
- Tener en cuenta validación de que si es por meses no puedes alquilar 1mes y Xdías, pagarías 2 meses

- [x] Validación de alquileres para evitar que se pueda alquilar en las 24h siguientes
- [x] Los espacios que sean alquilables por horas deben tener obligatoriamente los atributos horaInicio y horaFin
- [x] Validación de que los alquileres por horas deben estar entre horaInicio y horaFin
- [x] Validación de que la horaInicio debe ser anteior a la horaFin
- [x] Constraint de que el amount de los items no puede ser menor a 1
- [x] Modificar el smartSearch con el nuevo modelo de Items (línea 209)
- [x] Tener en cuenta el número de items a almacenar a la hora de sumar los metros para buscar espacio en smartSearch (linea 100)
## Imágenes
No procede

**Comment by alesancor1** [comment]
Resuelto en #47
