### ISSUE TITLE
A15.1 - Implementación del chat

### ISSUE THREAD

**Issue by tomgalbar** [Stacking-Up/data-service#44]
## Detalles
Se deberá desarrollar e implementar un sistema de chat para que los usuarios puedan hablar entre si de manera privada. A continuación, se detallan las subtareas:

## Subtareas
- [x] Setup ChatDB
- [x] Diseñar ChatDB Schemas
- [x] Conectar ChatDB y exponer socket

## Imágenes
No procede

**Comment by alesancor1** [comment]
Chat implementado. La integración con el resto de servicios en Docker se realiza en https://github.com/Stacking-Up/infrastructure
