### ISSUE TITLE
A3.4 - Endpoints

### ISSUE THREAD

**Issue by tomgalbar** [Stacking-Up/data-service#8]
Implementar los endpoints del Data Service.

* Users
- [x] GET /api/v1/users
- [x] GET /api/v1/users/{userId}
- [x] GET /api/v1/users/{userId}/items
- [x] GET /api/v1/users/{userId}/item/{itemId}
- [x] GET /api/v1/users/{userId}/ratings
- [x] GET /api/v1/users/{userId}/ratings/{ratingId}
- [x] GET /api/v1/users/{userId}/spaces
- [x] GET /api/v1/users/{userId}/spaces/{spaceId}
- [x] GET /api/v1/users/{userId}/rentals
- [x] GET /api/v1/users/{userId}/rentals/{rentalId}

* Spaces
- [x] GET /api/v1/spaces
- [x] GET /api/v1/spaces/{spaceId}
- [x] GET /api/v1/spaces/{spaceId}/rentals

* Rentals
- [x] GET /api/v1/rentals
- [x] GET /api/v1/rentals/{rentalId}

**Comment by alesancor1** [comment]
Tarea finalizada correctamente. Ver #26
